# -*- coding: utf-8 -*-
"""ml-iris_decision_tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMlfAY36pTIbxhKhCtnbv0Zt-apHmva6
"""

# 1. 필수 라이브러리 불러오기

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 2. 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

# 3. 독립변수(X)와 종속변수(y) 분리
X = df.drop(columns=['species'])
y = df['species']

# 4. 학습용/테스트용 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5. 모델 학습
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# 6. 예측
y_pred = model.predict(X_test)

# 7. 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print("✅ 분류 정확도:", accuracy)

# 8. 실제값 vs 예측값 비교 (앞 5개)
print("실제:", list(y_test[:5]))
print("예측:", list(y_pred[:5]))