# -*- coding: utf-8 -*-
"""titanic_rf_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFBrZovtbEbE__KvU5acqcRwT1TMV1L-
"""

import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print(train.head())

# 생존 여부는 'Survived' 컬럼
# 불필요한 열 제거
X = train.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin', 'Survived'])
y = train['Survived']

# 결측치 처리
X['Age'].fillna(X['Age'].median(), inplace=True)
X['Embarked'].fillna(X['Embarked'].mode()[0], inplace=True)

# 범주형 인코딩 (Sex, Embarked)
X = pd.get_dummies(X, columns=['Sex', 'Embarked'])

X.head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 학습/검증 데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 모델 훈련
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 정확도 출력
print("정확도:", accuracy_score(y_test, y_pred))

